- hosts: webservers
  become: true
  tasks:
    - name: Pull an image
      community.docker.docker_image:
        name: redmine
        source: pull

    - name: Create a config file
      ansible.builtin.template:
        src: .env.example
        dest: .env

    - name: Create a directory for cloud certificate
      ansible.builtin.file:
        path: .postgresql
        state: directory

    - name: Download a cloud certificate
      ansible.builtin.get_url:
        url: https://storage.yandexcloud.net/cloud-certs/CA.pem
        dest: .postgresql/root.crt
        mode: 0600

    - name: Restart a container
      docker_container:
        name: app
        image: redmine
        state: started
        restart: yes
        env_file: .env
        ports:
          - "80:3000"

