- hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{datadog_key}}"
    datadog_site: "datadoghq.eu"
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: [ 'ssh', 'sshd' ]
          - name: syslog
            search_string: [ 'rsyslog' ]
            cpu_check_interval: 0.2
            exact_match: true
            ignore_denied_access: true
